name: todo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  core_ui:
    path: ../../packages/core_ui
  core_utils:
    path: ../../packages/core_utils
  data:
    path: ../../packages/data
  domain:
    path: ../../packages/domain
  features_todo_app:
    path: ../../packages/features_todo_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
